=== function grimoire_plantsDescription(plant)
{
     - greenhouse_findedCultivables hasnt plant:
            ~ return ""
        
    - else:
        {plant:

            - BaccaDellaAddolorata: 
                ~ return "Il cambiamento a volte è come ghiaccio nelle vene: si infila nelle spalle, nelle gambe, non permette di avanzare.La strada è lì, eppure non riusciamo a fare il primo passo.La <b><i>Bacca dell'Addolorata</b></i> ci invita a fare prendere un respiro, e iniziare.È facile trovarla all'incrocio fra più strade. In passato veniva piantata dalle madri quando l3 figli3 diventavano grandi, così che non avessero paura di iniziare il loro cammino.Il nome è frutto di una falsa credenza: si dice che la bacca al suo centro cresca solo se la madre piange di dolore per la perdita dellə figliə.Ma anche la gioia di una madre che accoglie una nuova vita per sé rende la pianta rigogliosa."
            
            - BarbaDellInciampo:
                ~ return "<b><i>Barba dell'Inciampo.</b></i>È difficile resistere al richiamo della colpa. La colpa ci offre punizioni facili, la colpa ci rende vittime ammirabili. Il pianto dellə penitente porta alla redenzione. E a nessun cambiamento. La <b><i>Barba dell'Inciampo</b></i> è velenosa, tossica, tagliente. Almeno fino a quando non fruttifica. Fino a quando i processi interni, lentamente, non trasformano le sue foglie pericolose in un calice, il suo fiore appuntito in profumo e morbidezza. Ogni persona che intraprende il cammino ha bisogno di impararlo: la colpa non porta cambiamento, la responsabilità, sì. Riconoscere ciò che si è fatto, affrontarlo, chiedere scusa: non c'è riscrittura più potente."
                
            - BastoneDellOzioso:
                ~ return "<b><i>Bastone dell'Ozioso.</b></i>Ci sono poche parole più odiate ai nostri giorni di <i>ozio</i>. Eppure l'ozio è fondamentale: per ascoltare, per riposare, per immaginare. Per aver spazio per ricordare. Per scoprire il bello di ciò che ci circonda. E soprattutto: l'ozio è per il piacere di essere ozio. C'è un momento del fare, e un momento per non fare. Meglio ancora: il <i><b>Bastone dell'Ozioso</i></b> ci insegna che c'è un tempo in cui fare per il solo e unico piacere di fare. Non per soldi né per un riconoscimento sociale. Il momento per stonare, danzare male, disegnare senza scopo, scrivvere erando. Il tempo per cazzeggiare, il diritto di fare male. Volete sopravvivere in ufficio? Riempite lo spazio di questi bellissimi giunchi (i loro pollini corrodono il rame, e vi regaleranno ore senza elettricità e senza lavoro)."
                    
            - BrinaDellImpossibile:
                ~ return "Nessunə fiorista venderà mai della <b><i>Brina dell'Impossibile</i></b>. Eppure ne avremmo tutt3 bisogno, perché poch3 di noi conoscono una vita priva di traumi. La concezione comune è che sia un'infestante pericolosa dalle foglie taglienti. Invece la <b><i>Brina</b></i> è una pianta che cura. Non crea le ferite ma ci mostra quelle già esistenti, i traumi che prima non sapevamo vedere. È vero: più la ferita è vecchia e più farà male. Ma solo guardandola potremo iniziare a guarire, a ripartire. E quando possibile, a fare pace col passato. Forse anche per questo i suoi semi germogliano con estrema facilità. (Nota: chiedere a K. perché questa pianta è così amata dai gruppi rivoluzionari)"
                
            - CantoDelleCompagne: 
                ~ return "Se potesse parlare, <b><i>Canto delle Compagne</b></i> urlerebbe. Di gioia, di festa e di liberazione. Di rabbia. <b><i>Canto</b></i> è anche danza, è il movimento di chi si è sentitə dire di restare fermə, di non dare fastidio, di non fare rumore. È unione, distruzione, gioia. L3 amich3 unit3 nella rivolta"

            - CardoAspinato:
                ~ return "Potrebbe sorprendervi, ma la storia del <b><i>Cardo Aspinato</b></i> è una storia di costanti fraintendimenti. Da secoli viene usato come afrodisiaco, e per questo viene coltivato con metodi rigidi e severi per far sì che non entri mai nella fase di infiorescenza, che coincide con la perdita del suo vigore. Da quando poi è diventata pianta simbolo del Movimento per la Rinascita Maschile (sob), centinaia di alchimisti sono al lavoro per selezionarne varianti che siano sempre più grosse, rigide, turgide.Dimostrando di aver frainteso tutti gli insegnamenti che il <b><i>Cardo</b></i> può offrirci. Perché bloccare la povera pianta in un'eterna adolescenza significa non permetterle di fiorire e accogliere le sue vulnerabilità. Il fiore del <b><i>Cardo</b></i> sboccia solo quando le spine e il suo stelo si ammorbidiscono. E a quel punto le api si riempiono del suo nettare, e gli animali del bosco si avvicinano per strusciarsi sui filamenti morbidi, facendo sì che possa restare al caldo, e superare l'inverno. Forte nella sua vulnerabilità."
                
            - EderaDelleAmanti:
                ~ return "Quanto potere c'è in corpi che si giocano a vicenda, nel desiderio e nel piacere? <b><i>Edera delle amanti</b></i> tradizionalmente è associata al piacere fisico. Da queste parti si racconta che l'universo intero sia fatto d'edera. E che l'edera rimarrà in vita fino a quando le amanti saranno capaci di darsi amore e piacere. Ma il piacere è un motore semplice, se sappiamo ascoltarci. Ed <b><i>Edera</b></i> allora può invitarci a godere del cibo, del cielo, di una camminata. Di un momento da solə."
        
            - ErbaLiccia:
                ~ return "La prima volta che ho raccolto dell'<b><i>Erba Liccia</b></i>, la Somma Sacerdotessa mi ha donato un telaio. Era vecchio, il legno pieno di macchie, ma a distanza di anni è ancora con me. L'<b><i>Erba Liccia</b></i> è difficile da tessere, ma resistente. I tessuti migliori nascono quando si sa seguire la natura delle fibre, lasciando che sia l'erba stessa a dirci che forma darle. È il tessuto con cui creiamo i mantelli dell3 novizi3, e non per caso: l'<b><i>Erba Liccia</b></i> ci invita a intrecciare la nostra storia secondo la nostra natura, accettando ciò a cui serve rinunciare, abbracciando ciò che vogliamo portare. Passato, presente e futuro si trasformano così nella trama della nostra identità, della nostra unicità. Inoltre, le sue radici aeree sono ottime per fare decotti per chi ha bisogno di fare pace con sé stessə."
                
            - FalsaPalude:
                ~ return "La <b><i>Falsa Palude</i></b> è un piccolo miracolo della natura. Unico corallo di terra a noi conosciuto, è il risultato di una collaborazione senza verticalità, senza distruzione. Dalla sua scoperta tutto sommato recente è diventato il simbolo di numerose congreghe femministe e queer: tanto per una congrega quanto per una colonia di polipi, l'esperienza personale emerge in qualcosa di trasformativo solo quando vengono riconosciute le dinamiche e le oppressioni strutturali. Inoltre la <b><i>Falsa Palude</i></b> è capace di portare vita nei luoghi più desolati: ex centrali nucleari, vecchie miniere, i convegni del Movimento per la Rinascita Maschile."

            - LanaNotturna:
                ~ return "La <b><i>Lana Notturna</i></b> è così comune da averci abituato alla sua stranezza: un filo sottile, nemmeno particolarmente coriaceo, che regge un fiore ampio e soffice. Dovrebbe stupirci ancora di più il <i>dove</i> questa pianta cresce: nei luoghi ventosi, negli spazi abbandonati, nelle aree dove sono avvenuti grossi incidenti. Viene volgarmente chiamata <i>Regina delle discariche</i>, e anche se è un nome che detesto, ci racconta meglio quello che sa fare: crescere dove sembra non esserci spazio per la vita. <b><i>Lana Notturna</i></b> ci ricorda che anche quando tutto è perduto, qualcosa sta già cambiando. Bisogna dargli il tempo, e tutto saprà sbocciare."        
                            
            - LicheneDegliAbissi:
                ~ return "Si chiama <b><i>Lichene degli abissi</b></i>, anche se è a tutti gli effetti una cactaceae, per via di una leggenda popolare. Si dice che Luna e Sole si cerchino in cielo in un susseguirsi di odio e amore che esplode nelle eclissi: un amplesso focoso per quelle di Luna, e una furia violenta per quelle di Sole. All'alba dei tempi questa relazione è stata così distruttiva da lasciar crescere solo una pianta: un piccolo lichene dai fiori a cuore e dai frutti come lame. E da questa pianta si è generata poi la vita per come la conosciamo. Ora: non sono una persona romantica, e forse per questo mi viene da pensare che se una relazione è così incasinata, invece di inseguirsi come Luna e Sole potrebbe essere il caso di fermarsi, e capire se sia il caso di continuare e in altri modi, o chiuderla per sempre. I fiori di questa pianta puzzano, i frutti sono velenosi (per quanto ricchi di azoto, amato dalle piante): non è un monito sufficiente?"
                
            - NonTiScordarDiTe:
                ~ return "Fino a non molto tempo fa <b><i>Non ti scordar di te</b></i> popolava i nostri cimiteri, ma una cultura del grigiume e una formale mestizia ci hanno spint3 a disprezzare i suoi colori caleidoscopici, ritenuti non consoni al dolore del lutto. Fraintendendo completamente storia e messaggio di questa insolita pianta. Perché <b><i>Non ti scordar di te</b></i> è una collaborazione radicale, un insieme di radici aeree che sviluppa rami e corpi fruttiferi sotto terra. I falsi fiori che sbocciano sulle sue radici sono l'incubo di ogni alchimista, perché ognuno ha proprietà imprevedibili, condizionate dalle radici che l'hanno generato. <b><i>Non ti scordar di te</b></i> è un tripudio di vita, una pianta che parla di interconnessione, del fatto che ognunə di noi è l'eredità vivente delle persone che ha incontrato lungo il suo cammino. È immortalità nella comunità. Ed è anche l'invito a chiederci: quale traccia vorrò lasciare di me, quando non ci sarò più?"

            - Olobino:
                ~ return "(Nota: chiedere alla editor se sia legale condividere consigli di coltivazione). L'<i><b>Olobino</i></b> non andrebbe spiegato, ma provato. Questo fungo grigiastro, anonimo, è forse il miglior compagno per un risveglio spirituale. I suoi infiniti nomi popolari raccontano quanto sia stato centrale nelle nostre culture: Guida d'Oro, Occhio del Saggio, Lingua della Dea, Amorino, Pacificatore, Terrore del Prete. Personalmente, chiunque dovrebbe provarlo almeno una volta per vedersi con un amore incondizionato, per amare il mondo incondizionatamente. Per comprendere cosa si intende per <i>dissoluzione dell'ego</i>."

            - LaSpazzata: 
                ~ return "Ci sono pensieri che feriscono. Che alimentano sé stessi fino a diventare terremoti, valanghe, diluvi. E quando qualcosa li fa tremare, travolgono tutto ciò che incontrano, senza distinzione. <b><i>Spazzata</b></i> è dolorosa, ma come ogni dolore ci invita a prestare attenzione. A capire cosa liberare, prima che una piccola goccia si trasformi in valanga. (Appunto per la editor: specificare da qualche parte che La<b><i>Spazzata</b></i> non è l'insieme di foglie, ma il micelio che sgretola e distrugge rocce e muri. Le foglie sono solo organismi simbionti che prosperano sulla debolezza lasciata dal fungo.)"
            
            - universalIngredient:
                ~ return "La <b></i>Zandelia</i></b>, chiamata anche <i>Fior del Ricordo</i> è una spezia tanto rara quanto potente, capace di portare alla memoria il ricordo più bello vissuto da quella persona. In passato era la protagonista delle Zandeliore, giornate di festa collettiva a inizio primavera, pensate per condividere assieme momenti di gioia, e superare le tensioni dell'inverno."
                        
    }
}
