//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Rework/Components/DialogueBox/InputActionsDialogueBox.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Selania.Rework.Components.DialogueBox
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Rework/Components/DialogueBox/InputActionsDialogueBox.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @InputActionsDialogueBox: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @InputActionsDialogueBox()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputActionsDialogueBox"",
    ""maps"": [
        {
            ""name"": ""ContinueMap"",
            ""id"": ""c629b323-1436-418b-825b-6cdadd86e44f"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""efe02547-9a1a-4bb8-88f0-1e1797c7331e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dd3d38d8-872f-40af-8ea4-d8592f7c792f"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b320c705-0e91-4916-9f3d-7e8f90baa7ce"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4e30ec5-39de-472a-aeea-0508097f3656"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ChoicesSelectionMap"",
            ""id"": ""8404a136-508a-44bf-9aae-baf9966f15e1"",
            ""actions"": [
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""9bfa1134-15a9-4651-a3b8-460e8da882d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""31c6c6ab-0c03-4ca9-847c-82b236a9db85"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3"",
                    ""type"": ""Button"",
                    ""id"": ""2e0bef45-b1bc-4db7-95c0-5b15b95f3e89"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4"",
                    ""type"": ""Button"",
                    ""id"": ""b6499930-8094-4987-b058-060b130de83b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5"",
                    ""type"": ""Button"",
                    ""id"": ""9dfc2258-d189-4b92-aa85-7477d75db74a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6"",
                    ""type"": ""Button"",
                    ""id"": ""923dae47-22f4-42ee-b754-dbdfd1e01446"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7"",
                    ""type"": ""Button"",
                    ""id"": ""c16d39ef-8937-4646-a110-a8e4119b1969"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8"",
                    ""type"": ""Button"",
                    ""id"": ""7fd66a8e-41b0-410b-a2a3-c6e4d7e99c11"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9"",
                    ""type"": ""Button"",
                    ""id"": ""b00933a3-8bc3-4f64-9489-c5e62531e74d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""0"",
                    ""type"": ""Button"",
                    ""id"": ""d497b45e-757f-4f73-b393-4f2bce0a52b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""a"",
                    ""type"": ""Button"",
                    ""id"": ""072efaad-a962-4ebd-a926-21cd4c085a15"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""b"",
                    ""type"": ""Button"",
                    ""id"": ""7ef455a8-cefc-418c-b534-e3b255fe91d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""c"",
                    ""type"": ""Button"",
                    ""id"": ""a9908e6b-fd35-4a76-85d2-37677e6df0b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""d"",
                    ""type"": ""Button"",
                    ""id"": ""d2108839-9c8a-4e39-8247-8f8a2a7728ac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""e"",
                    ""type"": ""Button"",
                    ""id"": ""c274a234-899f-45e9-b796-c78f9504f13e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""f"",
                    ""type"": ""Button"",
                    ""id"": ""7b81eea2-9835-43fe-9f7d-972ac5bdddbe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""611be9e5-b6f1-4788-a8af-799f9f2c5fd3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb5cdc9b-8039-4755-9c4d-085585f32097"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c96b242-62c1-480e-9235-a96d0cf7ba14"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15e32ade-eab2-4646-a61f-6ba79365d9bf"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3f401d4-4383-426b-b5a1-da2b3e660529"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e9fb6b7-1d05-4795-872e-0cf42ca83ed4"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63a83905-83d8-4fda-adc4-f31fb12e1edf"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af7ef5fd-c170-42c6-a0d5-32235cfe9a78"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""590e8e3d-cc2c-4b5d-b043-bdeaf8d8ec5e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ce83be9-7576-47fe-8da9-afe41ebd2fa3"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f58802-3dc0-4f47-8f98-b3aae4602d2d"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b83b8948-4488-4621-b3fa-01d5a6987c5c"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0e58463-3b0c-4551-9044-0279cb4f969a"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce645354-df78-443f-8682-e7890466a95c"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2092d610-5f84-421c-bbb2-01154bca7b1e"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aec491e3-ad0a-4f9e-8a64-6347ed0a7548"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04fc8cb4-42f0-4263-9251-b40f01590697"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b27813f-dbee-4bc5-bd7f-c7d902446e67"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50337f8c-7887-4fb1-9019-0ffdb90a4031"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055d48f9-83ed-477b-b356-37fa8ddc4063"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""316f85b2-a519-4eba-98fa-669d4ab7b887"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""a"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a44287e2-149b-441e-9f15-789a1f42f52f"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""b"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1298e403-25ae-4753-a27c-62d62f9faab4"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""c"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""391db7b7-79ac-47c4-93af-5c552fa90a44"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45e182a6-87d2-40c4-9437-5ab0f88ebafd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""e"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ed0f5e8-1618-47ab-8ded-1b779f1361a0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""f"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // ContinueMap
            m_ContinueMap = asset.FindActionMap("ContinueMap", throwIfNotFound: true);
            m_ContinueMap_Continue = m_ContinueMap.FindAction("Continue", throwIfNotFound: true);
            // ChoicesSelectionMap
            m_ChoicesSelectionMap = asset.FindActionMap("ChoicesSelectionMap", throwIfNotFound: true);
            m_ChoicesSelectionMap__1 = m_ChoicesSelectionMap.FindAction("1", throwIfNotFound: true);
            m_ChoicesSelectionMap__2 = m_ChoicesSelectionMap.FindAction("2", throwIfNotFound: true);
            m_ChoicesSelectionMap__3 = m_ChoicesSelectionMap.FindAction("3", throwIfNotFound: true);
            m_ChoicesSelectionMap__4 = m_ChoicesSelectionMap.FindAction("4", throwIfNotFound: true);
            m_ChoicesSelectionMap__5 = m_ChoicesSelectionMap.FindAction("5", throwIfNotFound: true);
            m_ChoicesSelectionMap__6 = m_ChoicesSelectionMap.FindAction("6", throwIfNotFound: true);
            m_ChoicesSelectionMap__7 = m_ChoicesSelectionMap.FindAction("7", throwIfNotFound: true);
            m_ChoicesSelectionMap__8 = m_ChoicesSelectionMap.FindAction("8", throwIfNotFound: true);
            m_ChoicesSelectionMap__9 = m_ChoicesSelectionMap.FindAction("9", throwIfNotFound: true);
            m_ChoicesSelectionMap__0 = m_ChoicesSelectionMap.FindAction("0", throwIfNotFound: true);
            m_ChoicesSelectionMap_a = m_ChoicesSelectionMap.FindAction("a", throwIfNotFound: true);
            m_ChoicesSelectionMap_b = m_ChoicesSelectionMap.FindAction("b", throwIfNotFound: true);
            m_ChoicesSelectionMap_c = m_ChoicesSelectionMap.FindAction("c", throwIfNotFound: true);
            m_ChoicesSelectionMap_d = m_ChoicesSelectionMap.FindAction("d", throwIfNotFound: true);
            m_ChoicesSelectionMap_e = m_ChoicesSelectionMap.FindAction("e", throwIfNotFound: true);
            m_ChoicesSelectionMap_f = m_ChoicesSelectionMap.FindAction("f", throwIfNotFound: true);
        }

        ~@InputActionsDialogueBox()
        {
            UnityEngine.Debug.Assert(!m_ContinueMap.enabled, "This will cause a leak and performance issues, InputActionsDialogueBox.ContinueMap.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_ChoicesSelectionMap.enabled, "This will cause a leak and performance issues, InputActionsDialogueBox.ChoicesSelectionMap.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // ContinueMap
        private readonly InputActionMap m_ContinueMap;
        private List<IContinueMapActions> m_ContinueMapActionsCallbackInterfaces = new List<IContinueMapActions>();
        private readonly InputAction m_ContinueMap_Continue;
        /// <summary>
        /// Provides access to input actions defined in input action map "ContinueMap".
        /// </summary>
        public struct ContinueMapActions
        {
            private @InputActionsDialogueBox m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ContinueMapActions(@InputActionsDialogueBox wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "ContinueMap/Continue".
            /// </summary>
            public InputAction @Continue => m_Wrapper.m_ContinueMap_Continue;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_ContinueMap; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ContinueMapActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ContinueMapActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ContinueMapActions" />
            public void AddCallbacks(IContinueMapActions instance)
            {
                if (instance == null || m_Wrapper.m_ContinueMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ContinueMapActionsCallbackInterfaces.Add(instance);
                @Continue.started += instance.OnContinue;
                @Continue.performed += instance.OnContinue;
                @Continue.canceled += instance.OnContinue;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ContinueMapActions" />
            private void UnregisterCallbacks(IContinueMapActions instance)
            {
                @Continue.started -= instance.OnContinue;
                @Continue.performed -= instance.OnContinue;
                @Continue.canceled -= instance.OnContinue;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ContinueMapActions.UnregisterCallbacks(IContinueMapActions)" />.
            /// </summary>
            /// <seealso cref="ContinueMapActions.UnregisterCallbacks(IContinueMapActions)" />
            public void RemoveCallbacks(IContinueMapActions instance)
            {
                if (m_Wrapper.m_ContinueMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ContinueMapActions.AddCallbacks(IContinueMapActions)" />
            /// <seealso cref="ContinueMapActions.RemoveCallbacks(IContinueMapActions)" />
            /// <seealso cref="ContinueMapActions.UnregisterCallbacks(IContinueMapActions)" />
            public void SetCallbacks(IContinueMapActions instance)
            {
                foreach (var item in m_Wrapper.m_ContinueMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ContinueMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ContinueMapActions" /> instance referencing this action map.
        /// </summary>
        public ContinueMapActions @ContinueMap => new ContinueMapActions(this);

        // ChoicesSelectionMap
        private readonly InputActionMap m_ChoicesSelectionMap;
        private List<IChoicesSelectionMapActions> m_ChoicesSelectionMapActionsCallbackInterfaces = new List<IChoicesSelectionMapActions>();
        private readonly InputAction m_ChoicesSelectionMap__1;
        private readonly InputAction m_ChoicesSelectionMap__2;
        private readonly InputAction m_ChoicesSelectionMap__3;
        private readonly InputAction m_ChoicesSelectionMap__4;
        private readonly InputAction m_ChoicesSelectionMap__5;
        private readonly InputAction m_ChoicesSelectionMap__6;
        private readonly InputAction m_ChoicesSelectionMap__7;
        private readonly InputAction m_ChoicesSelectionMap__8;
        private readonly InputAction m_ChoicesSelectionMap__9;
        private readonly InputAction m_ChoicesSelectionMap__0;
        private readonly InputAction m_ChoicesSelectionMap_a;
        private readonly InputAction m_ChoicesSelectionMap_b;
        private readonly InputAction m_ChoicesSelectionMap_c;
        private readonly InputAction m_ChoicesSelectionMap_d;
        private readonly InputAction m_ChoicesSelectionMap_e;
        private readonly InputAction m_ChoicesSelectionMap_f;
        /// <summary>
        /// Provides access to input actions defined in input action map "ChoicesSelectionMap".
        /// </summary>
        public struct ChoicesSelectionMapActions
        {
            private @InputActionsDialogueBox m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ChoicesSelectionMapActions(@InputActionsDialogueBox wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_1".
            /// </summary>
            public InputAction @_1 => m_Wrapper.m_ChoicesSelectionMap__1;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_2".
            /// </summary>
            public InputAction @_2 => m_Wrapper.m_ChoicesSelectionMap__2;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_3".
            /// </summary>
            public InputAction @_3 => m_Wrapper.m_ChoicesSelectionMap__3;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_4".
            /// </summary>
            public InputAction @_4 => m_Wrapper.m_ChoicesSelectionMap__4;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_5".
            /// </summary>
            public InputAction @_5 => m_Wrapper.m_ChoicesSelectionMap__5;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_6".
            /// </summary>
            public InputAction @_6 => m_Wrapper.m_ChoicesSelectionMap__6;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_7".
            /// </summary>
            public InputAction @_7 => m_Wrapper.m_ChoicesSelectionMap__7;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_8".
            /// </summary>
            public InputAction @_8 => m_Wrapper.m_ChoicesSelectionMap__8;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_9".
            /// </summary>
            public InputAction @_9 => m_Wrapper.m_ChoicesSelectionMap__9;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/_0".
            /// </summary>
            public InputAction @_0 => m_Wrapper.m_ChoicesSelectionMap__0;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/a".
            /// </summary>
            public InputAction @a => m_Wrapper.m_ChoicesSelectionMap_a;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/b".
            /// </summary>
            public InputAction @b => m_Wrapper.m_ChoicesSelectionMap_b;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/c".
            /// </summary>
            public InputAction @c => m_Wrapper.m_ChoicesSelectionMap_c;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/d".
            /// </summary>
            public InputAction @d => m_Wrapper.m_ChoicesSelectionMap_d;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/e".
            /// </summary>
            public InputAction @e => m_Wrapper.m_ChoicesSelectionMap_e;
            /// <summary>
            /// Provides access to the underlying input action "ChoicesSelectionMap/f".
            /// </summary>
            public InputAction @f => m_Wrapper.m_ChoicesSelectionMap_f;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_ChoicesSelectionMap; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ChoicesSelectionMapActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ChoicesSelectionMapActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ChoicesSelectionMapActions" />
            public void AddCallbacks(IChoicesSelectionMapActions instance)
            {
                if (instance == null || m_Wrapper.m_ChoicesSelectionMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ChoicesSelectionMapActionsCallbackInterfaces.Add(instance);
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
                @_3.started += instance.On_3;
                @_3.performed += instance.On_3;
                @_3.canceled += instance.On_3;
                @_4.started += instance.On_4;
                @_4.performed += instance.On_4;
                @_4.canceled += instance.On_4;
                @_5.started += instance.On_5;
                @_5.performed += instance.On_5;
                @_5.canceled += instance.On_5;
                @_6.started += instance.On_6;
                @_6.performed += instance.On_6;
                @_6.canceled += instance.On_6;
                @_7.started += instance.On_7;
                @_7.performed += instance.On_7;
                @_7.canceled += instance.On_7;
                @_8.started += instance.On_8;
                @_8.performed += instance.On_8;
                @_8.canceled += instance.On_8;
                @_9.started += instance.On_9;
                @_9.performed += instance.On_9;
                @_9.canceled += instance.On_9;
                @_0.started += instance.On_0;
                @_0.performed += instance.On_0;
                @_0.canceled += instance.On_0;
                @a.started += instance.OnA;
                @a.performed += instance.OnA;
                @a.canceled += instance.OnA;
                @b.started += instance.OnB;
                @b.performed += instance.OnB;
                @b.canceled += instance.OnB;
                @c.started += instance.OnC;
                @c.performed += instance.OnC;
                @c.canceled += instance.OnC;
                @d.started += instance.OnD;
                @d.performed += instance.OnD;
                @d.canceled += instance.OnD;
                @e.started += instance.OnE;
                @e.performed += instance.OnE;
                @e.canceled += instance.OnE;
                @f.started += instance.OnF;
                @f.performed += instance.OnF;
                @f.canceled += instance.OnF;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ChoicesSelectionMapActions" />
            private void UnregisterCallbacks(IChoicesSelectionMapActions instance)
            {
                @_1.started -= instance.On_1;
                @_1.performed -= instance.On_1;
                @_1.canceled -= instance.On_1;
                @_2.started -= instance.On_2;
                @_2.performed -= instance.On_2;
                @_2.canceled -= instance.On_2;
                @_3.started -= instance.On_3;
                @_3.performed -= instance.On_3;
                @_3.canceled -= instance.On_3;
                @_4.started -= instance.On_4;
                @_4.performed -= instance.On_4;
                @_4.canceled -= instance.On_4;
                @_5.started -= instance.On_5;
                @_5.performed -= instance.On_5;
                @_5.canceled -= instance.On_5;
                @_6.started -= instance.On_6;
                @_6.performed -= instance.On_6;
                @_6.canceled -= instance.On_6;
                @_7.started -= instance.On_7;
                @_7.performed -= instance.On_7;
                @_7.canceled -= instance.On_7;
                @_8.started -= instance.On_8;
                @_8.performed -= instance.On_8;
                @_8.canceled -= instance.On_8;
                @_9.started -= instance.On_9;
                @_9.performed -= instance.On_9;
                @_9.canceled -= instance.On_9;
                @_0.started -= instance.On_0;
                @_0.performed -= instance.On_0;
                @_0.canceled -= instance.On_0;
                @a.started -= instance.OnA;
                @a.performed -= instance.OnA;
                @a.canceled -= instance.OnA;
                @b.started -= instance.OnB;
                @b.performed -= instance.OnB;
                @b.canceled -= instance.OnB;
                @c.started -= instance.OnC;
                @c.performed -= instance.OnC;
                @c.canceled -= instance.OnC;
                @d.started -= instance.OnD;
                @d.performed -= instance.OnD;
                @d.canceled -= instance.OnD;
                @e.started -= instance.OnE;
                @e.performed -= instance.OnE;
                @e.canceled -= instance.OnE;
                @f.started -= instance.OnF;
                @f.performed -= instance.OnF;
                @f.canceled -= instance.OnF;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ChoicesSelectionMapActions.UnregisterCallbacks(IChoicesSelectionMapActions)" />.
            /// </summary>
            /// <seealso cref="ChoicesSelectionMapActions.UnregisterCallbacks(IChoicesSelectionMapActions)" />
            public void RemoveCallbacks(IChoicesSelectionMapActions instance)
            {
                if (m_Wrapper.m_ChoicesSelectionMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ChoicesSelectionMapActions.AddCallbacks(IChoicesSelectionMapActions)" />
            /// <seealso cref="ChoicesSelectionMapActions.RemoveCallbacks(IChoicesSelectionMapActions)" />
            /// <seealso cref="ChoicesSelectionMapActions.UnregisterCallbacks(IChoicesSelectionMapActions)" />
            public void SetCallbacks(IChoicesSelectionMapActions instance)
            {
                foreach (var item in m_Wrapper.m_ChoicesSelectionMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ChoicesSelectionMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ChoicesSelectionMapActions" /> instance referencing this action map.
        /// </summary>
        public ChoicesSelectionMapActions @ChoicesSelectionMap => new ChoicesSelectionMapActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ContinueMap" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ContinueMapActions.AddCallbacks(IContinueMapActions)" />
        /// <seealso cref="ContinueMapActions.RemoveCallbacks(IContinueMapActions)" />
        public interface IContinueMapActions
        {
            /// <summary>
            /// Method invoked when associated input action "Continue" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnContinue(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ChoicesSelectionMap" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ChoicesSelectionMapActions.AddCallbacks(IChoicesSelectionMapActions)" />
        /// <seealso cref="ChoicesSelectionMapActions.RemoveCallbacks(IChoicesSelectionMapActions)" />
        public interface IChoicesSelectionMapActions
        {
            /// <summary>
            /// Method invoked when associated input action "1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_4(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_5(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_6(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_7(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_8(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_9(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void On_0(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "a" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnA(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "b" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnB(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "c" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnC(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnD(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "e" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnE(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "f" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnF(InputAction.CallbackContext context);
        }
    }
}
