            /*----------------------------------------
            
               Lista ingredienti e relativa traduzione
            
             ----------------------------------*/
//Lista dei doni che si possono trovare in gioco.
VAR findedGifts = ()


=== function ingredientTranslator(ingredient)
    {ingredient:
        - LaSpazzata: 
            ~ return "un rametto della Spezzata"
            
        - BaccaDellaAddolorata: 
            ~ return "una Bacca della Addolorata"
            
        - EderaDelleAmanti:
            ~ return "una foglia di Edera delle Amanti"
            
        - BrinaDellImpossibile:
            ~ return "un frammento di Brina dell'Impossibile"

        - CantoDelleCompagne: 
            ~ return "una goccia di Canto delle Compagne"
            
        - LicheneDegliAbissi:
            ~ return "una traccia dell'odore del Lichene degli Abissi"
            
        - NonTiScordarDiTe:
            ~ return "l'impronta del Non Ti Scordar di Te"
        
        - Cardo Aspinato:
            ~ return "un ciuffo di Cardo Aspinato"             
    
    }
