            /*----------------------------------------
            
               Lista ingredienti e relativa traduzione
            
             ----------------------------------*/
//Lista dei doni che si possono trovare in gioco.
VAR findedGifts = ()


=== function ingredientTranslator(ingredient)
    {ingredient:

        - BaccaDellaAddolorata: 
            ~ return "un seme di Bacca della Addolorata"
        
        - BarbaDellInciampo:
            ~ return "una spina di Barba dell'Inciampo"
            
        - BastoneDellOzioso:
            ~ return "un nodo di Bastone dell'Ozioso"
                
        - BrinaDellImpossibile:
            ~ return "un frammento di Brina dell'Impossibile"
            
        - CantoDelleCompagne: 
            ~ return "una goccia di Canto delle Compagne"

        - CardoAspinato:
            ~ return "un ciuffo di Cardo Aspinato"
            
        - EderaDelleAmanti:
            ~ return "una foglia di Edera delle Amanti"
    
        - ErbaLiccia:
            ~ return "scrivere qualcosa su Erba Liccia"
            
        - FalsaPalude:
            ~ return "un petalo di Falsa Palude"

        - LanaNotturna:
            ~ return "scrivere qualcosa su Lana Notturna"        
                        
        - LicheneDegliAbissi:
            ~ return "una traccia dell'odore del Lichene degli Abissi"
            
        - NonTiScordarDiTe:
            ~ return "l'impronta del Non Ti Scordar di Te"

        - Olobino:
            ~ return "un cappello di Olobino"

        - LaSpazzata: 
            ~ return "una foglia della Spezzata"
                        
    }
