            /*----------------------------------------
            
               Lista ingredienti e relativa traduzione
            
             ----------------------------------*/
//Lista dei doni che si possono trovare in gioco.
VAR findedGifts = ()


=== function ingredientTranslator(ingredient)
    {ingredient:
        - LaSpazzata: 
            ~ return "un residuo della Spezzata"
            
        - BaccaDellaAddolorata: 
            ~ return "una Bacca della Addolorata"
            
        - EderaDelleAmanti:
            ~ return "dell'Edera delle Amanti"
            
        - BrinaDellImpossibile:
            ~ return "della Brina dell'Impossibile"

        - CantoDelleCompagne: 
            ~ return "del Canto delle Compagne"
            
        - LicheneDegliAbissi:
            ~ return "del Lichene degli Abissi"
            
        - NonTiScordarDiTe:
            ~ return "del Non Ti Scordar di Te"     
    
    }
